### ISSUE TITLE
Is this Jordan from the UNSW Computer Science and Engineering lecture today? (it's the De La guy)

### ISSUE THREAD

**Issue by HighDensityAwesome** [BrainBoxBrown/Distributed-Fractal#1]
Sorry to ask here, didn't have any other avenues of easy accessibility (also, nice awesome fractal stuff).

**Comment by BrainBoxBrown** [comment]
Wow yes it is. Excellent job stalking me :)
Add me on facebook: Jordan Brown
My profile picture is me under water and my cover photo is an Ariel shot of my house from a drone

-  Jordan
